server:
  port: 9093

spring:
  config:
    import: optional:configserver:http://localhost:8085
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservice
  application:
    name: RATING-SERVICE

