server:
  port: 8082

spring:
  config:
    import: optional:configserver:http://localhost:8085
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  application:
    name: HOTEL-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true