server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | create-drop | update | validate | none
    show-sql: true